const PREFIX = 'Nito/App/';

export const TEST = `${PREFIX}TEST`;

export const SET_COLLECTION = `${PREFIX}SET_COLLECTION`;
export const SET_COLLECTION_ITEM = `${PREFIX}SET_COLLECTION_ITEM`;
export const SET_ITEM_REQUEST = `${PREFIX}SET_ITEM_REQUEST`;

export const UPDATE_COLLECTION = `${PREFIX}UPDATE_COLLECTION`;
export const UPDATE_COLLECTION_ITEM = `${PREFIX}UPDATE_COLLECTION_ITEM`;
export const UPDATE_ITEM_REQUEST = `${PREFIX}UPDATE_ITEM_REQUEST`;

export const REMOVE_COLLECTION = `${PREFIX}REMOVE_COLLECTION`;
export const REMOVE_COLLECTION_ITEM = `${PREFIX}REMOVE_COLLECTION_ITEM`;
export const REMOVE_ITEM_REQUEST = `${PREFIX}REMOVE_ITEM_REQUEST`;
